import Foundation
import AppKit
import CryptoKit

public class ClipboardManager: ObservableObject {
    public static let shared = ClipboardManager()
    
    private var lastChangeCount = NSPasteboard.general.changeCount
    private var timer: Timer?
    private var isWriting = false
    
    private init() {}
    
    public func startMonitoring() {
        guard timer == nil else { return }
        // Poll every 0.25 seconds for changes for responsive clipboard updates.
        timer = Timer.scheduledTimer(withTimeInterval: 0.25, repeats: true) { [weak self] _ in
            self?.checkPasteboard()
        }
        
        // Start monitoring for screenshot file creation
        ScreenshotMonitor.shared.startMonitoring()
    }
    
    public func stopMonitoring() {
        timer?.invalidate()
        timer = nil
        
        ScreenshotMonitor.shared.stopMonitoring()
    }
    
    public func writeWithoutMonitoring(_ block: () -> Void) {
        isWriting = true
        block()
        // Wait briefly for pasteboard count to register, then update lastChangeCount
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
            self.lastChangeCount = NSPasteboard.general.changeCount
            self.isWriting = false
        }
    }
    
    private func checkPasteboard() {
        guard !isWriting else { return }
        
        // Respect the pause history settings
        if UserDefaults.standard.bool(forKey: "isHistoryPaused") {
            // Keep lastChangeCount aligned so it doesn't trigger when resumed
            lastChangeCount = NSPasteboard.general.changeCount
            return
        }
        
        let currentCount = NSPasteboard.general.changeCount
        if currentCount != lastChangeCount {
            lastChangeCount = currentCount
            handleClipboardChange()
        }
    }
    
    private func handleClipboardChange() {
        let pasteboard = NSPasteboard.general
        
        // 1. Sensitivity / Password manager filter
        if isSensitive(pasteboard: pasteboard) {
            return
        }
        
        // 2. Classify and process
        // Check for Files
        if let fileURLs = pasteboard.readObjects(forClasses: [NSURL.self], options: [NSPasteboard.ReadingOptionKey.urlReadingFileURLsOnly: true]) as? [URL], !fileURLs.isEmpty {
            processFiles(fileURLs, pasteboard: pasteboard)
            return
        }
        
        // Check for URLs
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL], !urls.isEmpty {
            // Verify if there are HTTP/HTTPS URLs (exclude file URLs here as they are handled)
            let webURLs = urls.filter { $0.scheme == "http" || $0.scheme == "https" }
            if let webURL = webURLs.first {
                processURL(webURL, pasteboard: pasteboard)
                return
            }
        }
        
        // Check for Images
        // TIFF and PNG are the standard image pasteboard types on macOS
        if pasteboard.types?.contains(.png) == true || pasteboard.types?.contains(.tiff) == true {
            if let imgData = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff) {
                processImage(imgData, pasteboard: pasteboard)
                return
            }
        }
        
        // Check for Plain Text
        if let plainText = pasteboard.string(forType: .string), !plainText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            processText(plainText, pasteboard: pasteboard)
            return
        }
        
        // Check for general fallback types
        if let firstType = pasteboard.types?.first(where: { !$0.rawValue.contains("corepasteboard") }) {
            processOther(firstType, pasteboard: pasteboard)
        }
    }
    
    private func isSensitive(pasteboard: NSPasteboard) -> Bool {
        let sensitiveTypes = [
            "org.nspasteboard.TransientType",
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword"
        ]
        guard let types = pasteboard.types else { return false }
        for type in sensitiveTypes {
            if types.contains(NSPasteboard.PasteboardType(type)) {
                return true
            }
        }
        return false
    }
    
    private func processText(_ text: String, pasteboard: NSPasteboard) {
        let displayTitle = text.components(separatedBy: .newlines)
            .first(where: { !$0.trimmingCharacters(in: .whitespaces).isEmpty }) ?? text
        
        let characterCount = text.count
        let lineCount = text.components(separatedBy: .newlines).count
        let subtitle = lineCount > 1 ? "\(lineCount) lines, \(characterCount) chars" : "\(characterCount) characters"
        let calcResult = ExpressionParser.evaluate(text)
        
        let item = ClipboardItem(
            type: .text,
            textContent: text,
            displayTitle: String(displayTitle.prefix(100)),
            subtitle: subtitle,
            representations: extractRepresentations(from: pasteboard, forTypes: [.string]),
            calculationResult: calcResult
        )
        ClipboardStore.shared.add(item: item)
    }
    
    private func processURL(_ url: URL, pasteboard: NSPasteboard) {
        let item = ClipboardItem(
            type: .url,
            textContent: url.absoluteString,
            displayTitle: url.absoluteString,
            subtitle: url.host ?? "Web Link",
            representations: extractRepresentations(from: pasteboard, forTypes: [.string, .URL])
        )
        ClipboardStore.shared.add(item: item)
    }
    
    private func processFiles(_ urls: [URL], pasteboard: NSPasteboard) {
        let displayTitle: String
        let subtitle: String
        
        if urls.count == 1 {
            displayTitle = urls[0].lastPathComponent
            subtitle = urls[0].path
        } else {
            displayTitle = "\(urls[0].lastPathComponent) and \(urls.count - 1) other files"
            subtitle = "\(urls.count) file paths"
        }
        
        let textContent = urls.map { $0.absoluteString }.joined(separator: "\n")
        
        // Extract standard file pasteboard representations
        let typesToExtract = pasteboard.types?.filter { $0.rawValue == "NSFilenamesPboardType" || $0 == .fileURL } ?? []
        
        let item = ClipboardItem(
            type: .file,
            textContent: textContent,
            displayTitle: displayTitle,
            subtitle: subtitle,
            representations: extractRepresentations(from: pasteboard, forTypes: typesToExtract)
        )
        ClipboardStore.shared.add(item: item)
    }
    
    private func processImage(_ data: Data, pasteboard: NSPasteboard) {
        let id = UUID()
        // Save image to disk asynchronously to prevent blocking the clipboard monitor thread
        DispatchQueue.global(qos: .utility).async {
            guard let paths = ImageStorage.shared.saveImage(data: data, id: id) else { return }
            
            let digest = SHA256.hash(data: data)
            let hashString = digest.map { String(format: "%02x", $0) }.joined()
            
            let sizeDesc = ImageStorage.shared.getImageSizeDescription(path: paths.imagePath) ?? "Image"
            let item = ClipboardItem(
                id: id,
                type: .image,
                storagePath: paths.imagePath,
                displayTitle: "Image",
                subtitle: sizeDesc,
                representations: nil,
                contentHash: hashString
            )
            ClipboardStore.shared.add(item: item)
        }
    }
    
    private func processOther(_ type: NSPasteboard.PasteboardType, pasteboard: NSPasteboard) {
        guard let data = pasteboard.data(forType: type) else { return }
        
        let displayTitle = "Rich Data (\(type.rawValue.components(separatedBy: ".").last ?? type.rawValue))"
        let formatter = ByteCountFormatter()
        formatter.allowedUnits = [.useKB, .useMB]
        let subtitle = formatter.string(fromByteCount: Int64(data.count))
        
        let item = ClipboardItem(
            type: .other,
            displayTitle: displayTitle,
            subtitle: subtitle,
            representations: [type.rawValue: data]
        )
        ClipboardStore.shared.add(item: item)
    }
    
    private func extractRepresentations(from pb: NSPasteboard, forTypes types: [NSPasteboard.PasteboardType]) -> [String: Data] {
        var reps: [String: Data] = [:]
        for type in types {
            if let data = pb.data(forType: type) {
                reps[type.rawValue] = data
            }
        }
        return reps
    }
}
